version: '2'

services:
  vp:  # vp node no needing membersrvc
    #image: hyperledger/fabric-peer:latest
   #image: yeasy/hyperledger-fabric-peer:0.6-dp
   image: hyperledger/fabric-peer
   #image: ibmblockchain/fabric-peer:x86_64-0.6.1-preview
    restart: unless-stopped
    environment:
     # - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_LOGGING_LEVEL=info
     #  - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=noops
    expose:
      - "7050"  # Rest
      - "7051"  # Grpc
      - "7052"  # Peer CLI
      - "7053"  # Peer Event
    ports:
        - "7050:7050"
    volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
      - /var/run/docker.sock:/var/run/docker.sock
    command: peer node start  # this repeats the default cmd to make sure